### ISSUE TITLE
Images and names

### ISSUE THREAD

**Issue by ngajhede** [BlitZz96/Twitch-brb#1]
So, you can change your name on twitch now. I believe the best idea to pull info on a user/chatters is using their ID, and pull their names from that. 
I saw your //image? comment and found out images are called "logos" in the twich API. :) 

https://dev.twitch.tv/docs/v5/reference/users/#get-user

**Comment by BlitZz96** [comment]
Oh, I had no idea. Good observation!
Is there any username -> ID resolver we can use for this?
I suppose we will get this info from the serverside aka provided from the bot?

> I saw your //image? comment and found out images are called "logos" in the twich API. :)
You are correct! :D 

> https://dev.twitch.tv/docs/v5/reference/users/#get-user
As of my research. We cannot use this api endpoint. To use "get-user" you have to make the user authorize the app (Something that I don't believe is possible to do in the twitch chat)

If I am correct: The only way to use this will be to have the user go to an 3rd party site (ours) for Auth and do stuff there. It's possible, but is this the practice we want to use? Kida feels a bit bad UX

**Comment by ngajhede** [comment]
Im pretty busy right now, but i will look at it later. Maybe look how the app Twitch Giveaways did it.
If not a bot, we can always grab from the users chat directly? 

(https://github.com/darsain/twitch-giveaways)

**Comment by Nicholaiii** [comment]
The module i have in mind has support for that! :)

**Comment by BlitZz96** [comment]
Sweet! 👍
